Repository hetzneronline/community-content, pull requests merged in 2019-07, with the labels that each got.

#93 Nividia drivers on Ubuntu
  tutorials/nvidia-drivers-on-ubuntu/01.en.md
Labels: ready

#154 How To Install and Secure phpMyAdmin with Nginx on CentOS 7
  tutorials/install-and-secure-phpmyadmin-with-nginx-on-centos-7/01.en.md
  tutorials/install-and-secure-phpmyadmin-with-nginx-on-centos-7/secure-phpmyadmin-1.png
  tutorials/install-and-secure-phpmyadmin-with-nginx-on-centos-7/secure-phpmyadmin-2.png
  tutorials/install-and-secure-phpmyadmin-with-nginx-on-centos-7/secure-phpmyadmin-3.png
Labels: ready

#155 Installing NGINX with Brotli and Gzip compression on Ubuntu
  tutorials/install-nginx-with-brotli-and-gzip-compression-on-ubuntu/01.en.md
Labels: ready

#156 Translation (RU): Installing LAMP Stack on CentOS 7 (Single or Multiple Sites)
  tutorials/install-lamp-server-on-centos-7/01.en.md
  tutorials/install-lamp-server-on-centos-7/01.ru.md
Labels: official, translation

#160 Translation (RU): Basic configuration of a Debian server
  tutorials/debian-base-configuration-docker/01.de.md
  tutorials/debian-base-configuration-docker/01.en.md
  tutorials/debian-base-configuration-docker/01.ru.md
Labels: official, ready, translation

#118 Install and configure VMware vCenter
  tutorials/install-and-configure-vmware-vcenter/01.en.md
  tutorials/install-and-configure-vmware-vcenter/images/installer_1.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_10.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_11.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_12.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_13.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_14.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_15.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_2.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_3.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_4.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_5.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_6.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_7.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_8.png
  tutorials/install-and-configure-vmware-vcenter/images/installer_9.png
Labels: WIP

#147 How to use IPv6 in Docker using Proxmox and pfSense
  tutorials/docker-ipv6-securely/01.en.md
  tutorials/docker-ipv6-securely/images/Docker IPv6 Securely.png
  tutorials/docker-ipv6-securely/images/VMs.png
  tutorials/docker-ipv6-securely/images/bridges.png
  tutorials/docker-ipv6-securely/images/hetzner_ipv6.png
  tutorials/docker-ipv6-securely/images/lab.png
  tutorials/docker-ipv6-securely/images/pfsense.png
  tutorials/docker-ipv6-securely/images/pfsense_bridge.png
  tutorials/docker-ipv6-securely/images/pfsense_gateways.png
  tutorials/docker-ipv6-securely/images/pfsense_interfaces.png
  tutorials/docker-ipv6-securely/images/pfsense_interfaces2.png
  tutorials/docker-ipv6-securely/images/pfsense_routing.png
  tutorials/docker-ipv6-securely/images/pfsense_static_routes.png
  tutorials/docker-ipv6-securely/images/proxmox.png
Labels: ready

#167 Install LEMP Stack on Debian 10
  tutorials/install-lemp-stack-on-debian-10/01.en.md
Labels: ready

#164 How to Secure Nginx with Let's Encrypt on CentOS 7
  tutorials/secure-nginx-with-let-s-encrypt-on-centos-7/01.en.md
Labels: ready
