Repository hetzneronline/community-content, pull requests merged in 2019-08, with the labels that each got.

#168 Update 01.en.md
  tutorials/install-and-configure-proxmox_ve/01.en.md
Labels: ready

#165 How to Secure Nginx with Let's Encrypt on Ubuntu 18.04
  tutorials/secure-nginx-with-lets-encrypt-on-ubuntu-18-04/01.en.md
Labels: ready

#170 How to Secure Nginx with Let's Encrypt on Debian 10
  tutorials/secure-nginx-with-lets-encrypt-on-debian-10/01.en.md
Labels: ready

#171 How To Install R on Debian 10
  tutorials/how-to-install-r-on-debian-10/01.en.md
Labels: ready

#172 Added note to routed vmbr in proxmox tutorial
  tutorials/install-and-configure-proxmox_ve/01.de.md
  tutorials/install-and-configure-proxmox_ve/01.en.md
  tutorials/install-and-configure-proxmox_ve/01.ru.md
Labels: pending

#180 Added "How to route cloud server over private network using pfSense and Hetzner Cloud Networks"
  tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks/01.en.md
Labels: review wanted

#185 Route and NAT fix + Added Firewall rule for UI on WAN interface
  tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks/01.en.md
Labels: Existing tutorial

#175 Linux setup GRE tunnel
  tutorials/linux-setup-gre-tunnel/01.en.md
Labels: ready

#178 How To Install Git on Ubuntu 18.04
  tutorials/how-to-install-git-on-ubuntu-18.04/01.en.md
Labels: ready

#181 Tutorial: Install Docker CE on Debian Buster with Dualstack IPv6-NAT and Firewall Support
  tutorials/debian-buster-docker-install-dualstack-ipv6nat-firewall/01.en.md
Labels: ready

#169 Translation (RU): Run multiple Docker Compose services on Debian/Ubuntu
  tutorials/docker-compose-as-systemd-service/01.en.md
  tutorials/docker-compose-as-systemd-service/01.ru.md
Labels: official, translation

#187 Translation (IT): Linux setup tunnel GRE
  tutorials/linux-setup-gre-tunnel/01.en.md
  tutorials/linux-setup-gre-tunnel/01.it.md
Labels: Existing tutorial, translation
