Repository hetzneronline/community-content, pull requests merged in 2019-04, with the labels that each got.

#107 Add missing default IP addresses
  tutorial-template.md
Labels: review wanted

#100 Our own Gitlab Server with docker and traefik
  tutorials/gitlab-server-with-docker/01.en.md
  tutorials/gitlab-server-with-docker/images/docker_check.png
  tutorials/gitlab-server-with-docker/images/docker_install.png
  tutorials/gitlab-server-with-docker/images/docker_ps.png
Labels: ready

#10 Italian Translation
  tutorials/prosody-on-debian9/01.it.md
Labels: ready, translation

#108 Install SteamCMD [DE/EN] & Install CSGO Game Server [DE/EN]
  tutorials/install-gameserver-csgo/01.de.md
  tutorials/install-gameserver-csgo/01.en.md
  tutorials/install-steamcmd/01.de.md
  tutorials/install-steamcmd/01.en.md
Labels: ready

#109 How to Reset MySQL or MariaDB Root Password
  tutorials/how-to-reset-mysql-or-mariadb-root-password/01.en.md
Labels: ready

#110 Installation of the container management platform Rancher on Hetzner Cloud
  tutorials/hcloud-install-rancher-single/01.en.md
  tutorials/hcloud-install-rancher-single/images/step1.gif
  tutorials/hcloud-install-rancher-single/images/step2.gif
  tutorials/hcloud-install-rancher-single/images/step3.gif
  tutorials/hcloud-install-rancher-single/images/step4.gif
Labels: ready

#111 How To Install Linux, Nginx, MySQL, PHP (LEMP) stack On CentOS 7
  tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-centos-7/01.en.md
Labels: ready

#38 Add A basic guide to PHP Symfony
  tutorials/a-basic-guide-to-php-symfony/01.en.md
  tutorials/a-basic-guide-to-php-symfony/02.en.md
Labels: ready

#117 Fix issues with Prosody on Debian 9
  tutorials/prosody-on-debian9/01.en.md
  tutorials/prosody-on-debian9/01.it.md
Labels: Existing tutorial, ready

#113 How to install SinusBot on Linux [DE/EN]
  tutorials/install-sinusbot/01.de.md
  tutorials/install-sinusbot/01.en.md
  tutorials/install-sinusbot/SinusBot-cli.png
  tutorials/install-sinusbot/SinusBot-head.png
  tutorials/install-sinusbot/SinusBot-settings-instances.png
  tutorials/install-sinusbot/SinusBot-settings-pwreset.png
  tutorials/install-sinusbot/SinusBot-settings.png
  tutorials/install-sinusbot/SinusBot-webinterface.png
Labels: ready

#115 How to securing SSH on Linux systems [DE/EN]
  tutorials/howto-securing-ssh/01.de.md
  tutorials/howto-securing-ssh/01.en.md
Labels: ready

#114 How to Install Nagios 4.4.3 on CentOS 7
  tutorials/install-nagios-on-centos-7/01.en.md
Labels: ready
