Repository hetzneronline/community-content, pull requests merged in 2019-03, with the labels that each got.

#6 Real-Time Applications with Go and ReactJS (Part 1)
  assets/real-time-apps-with-go-and-reactjs.gif
  assets/real-time-apps-with-go-and-reactjs.mp4
  tutorials/real-time-apps-with-go-and-reactjs_part1.md
Labels: review wanted

#2 Add tutorial about docker-compose services via systemd service templates
  tutorials/DockerComposeAsSystemdService.md
Labels: review wanted

#3 Install and configure prosody on Debian (and extra features)
  tutorials/ProsodyOnDebian.md
Labels: review wanted

#11 Additional floating pool
  tutorials/private-cloud-additional-floating-pool/.de.md
  tutorials/private-cloud-additional-floating-pool/01.en.md
Labels: Importing from Wiki

#26 Restructured to new Naming Convention
  README.md
  assets/real-time-apps-with-go-and-reactjs.gif
  assets/real-time-apps-with-go-and-reactjs.mp4
  contribution-guidelines.md
  preview.jpg
  tutorial-template.md
  tutorials/docker-compose-as-systemd-service/01.en.md
  tutorials/prosody-on-debian9/01.en.md
  tutorials/real-time-apps-with-go-and-reactjs/01.en.md
Labels: ready

#13 Installing the r8168 driver
  tutorials/installing-the-r8168-driver/01.de.md
  tutorials/installing-the-r8168-driver/01.en.md
Labels: Importing from Wiki

#14 Lsi raid controller
  tutorials/lsi-raid-controller/01.de.md
  tutorials/lsi-raid-controller/01.en.md
Labels: Importing from Wiki

#15 Pro ftpd
  tutorials/install-and-configure-proftpd/01.de.md
  tutorials/install-and-configure-proftpd/01.en.md
Labels: Importing from Wiki

#17 Repairing a lvm volume
  tutorials/repairing-lvm-volumes/01.de.md
  tutorials/repairing-lvm-volumes/01.en.md
Labels: Importing from Wiki

#37 Remove "<br />" tag from prosody-on-debian9
  tutorials/prosody-on-debian9/01.en.md
Labels: ready

#16 Proxmox ve
  tutorials/install-and-configure-proxmox_ve/01.de.md
  tutorials/install-and-configure-proxmox_ve/01.en.md
Labels: Importing from Wiki

#12 Docker
  tutorials/install-and-configure-docker/01.de.md
  tutorials/install-and-configure-docker/01.en.md
Labels: Importing from Wiki

#7 Add hcloud-cli Tutorial
  tutorials/howto-hcloud-cli/01.en.md
Labels: ready

#25 Add How To Hetzner Cloud Terraform Provider
  tutorials/howto-hcloud-terraform/01.en.md
Labels: review wanted

#31 Install public NTP server and optionally add it to the NTP pool
  tutorials/install-public-ntp-server-on-debian-ubuntu/01.en.md
Labels: review wanted

#35 Install TURN/STUN server with coturn on Debian/Ubuntu
  tutorials/install-turn-stun-server-on-debian-ubuntu-with-coturn/01.en.md
Labels: review wanted

#46 Certificate of Origin added
  contributing.md
  tutorial-template.md
Labels: help wanted, review wanted

#18 Resize ext partition
  tutorials/resize-ext-partition/01.de.md
  tutorials/resize-ext-partition/01.en.md
Labels: Importing from Wiki

#19 Changing the tler time
  tutorials/changing-tler-time/01.de.md
  tutorials/changing-tler-time/01.en.md
Labels: Importing from Wiki

#20 Syncing the time with ntp
  tutorials/install-and-configure-ntp/01.de.md
  tutorials/install-and-configure-ntp/01.en.md
Labels: Importing from Wiki

#40 Borgbackup
  tutorials/install-and-configure-borgbackup/01.de.md
  tutorials/install-and-configure-borgbackup/01.en.md
Labels: Importing from Wiki

#42 Windows server remote desktop services
  tutorials/configuring-windows-remote-desktop-services/01.de.md
  tutorials/configuring-windows-remote-desktop-services/01.en.md
Labels: Importing from Wiki

#55 Change to correct domain
  tutorials/prosody-on-debian9/01.en.md
Labels: ready

#57 Hetzner Cloud CLI - wrong title and metadata
  tutorials/howto-hcloud-cli/01.en.md
Labels: ready

#56 Hetzner Cloud Terraform Provider - wrong metadata
  tutorials/howto-hcloud-terraform/01.en.md
Labels: ready

#28 Revert "Repairing a lvm volume"
  tutorials/repairing-lvm-volumes/01.de.md
  tutorials/repairing-lvm-volumes/01.en.md
Labels: Importing from Wiki, help wanted

#59 push tutorial lamp centos 7
  tutorials/install-lamp-server-on-centos-7/01.en.md
Labels: review wanted

#67 Rclone Tutorial
  tutorials/rclone-basics/01.en.md
  tutorials/rclone-basics/images/drive-oath.png
  tutorials/rclone-basics/images/drive-setup.png
  tutorials/rclone-basics/images/dropbox-local.png
  tutorials/rclone-basics/images/dropbox-setup.png
  tutorials/rclone-basics/images/grant-access.png
  tutorials/rclone-basics/images/headless-drive.png
  tutorials/rclone-basics/images/ls-file.png
  tutorials/rclone-basics/images/pick-remote.png
  tutorials/rclone-basics/images/rclone-config.png
  tutorials/rclone-basics/images/sample-move.png
Labels: ready

#68 Setup a mail server with Mailcow
  tutorials/setup-mailserver-with-mailcow/01.en.md
Labels: ready

#69 How to install Teamspeak 3 server software on Windows & Linux systems [DE/EN]
  tutorials/install-teamspeak3-server/01.de.md
  tutorials/install-teamspeak3-server/01.en.md
Labels: ready

#70 Added Outline VPN tutorial
  tutorials/install-outline-vpn-server/01.en.md
Labels: ready

#84 Add section about 'requesting' of content / help.
  README.md
Labels: review wanted

#88 Update metadata
  tutorials/changing-tler-time/01.de.md
  tutorials/changing-tler-time/01.en.md
  tutorials/configuring-windows-remote-desktop-services/01.de.md
  tutorials/configuring-windows-remote-desktop-services/01.en.md
  tutorials/debian-base-configuration-docker/01.de.md
  tutorials/debian-base-configuration-docker/01.en.md
  tutorials/docker-compose-as-systemd-service/01.en.md
  tutorials/howto-hcloud-cli/01.en.md
  tutorials/howto-hcloud-terraform/01.en.md
  tutorials/install-and-configure-borgbackup/01.de.md
  tutorials/install-and-configure-borgbackup/01.en.md
  tutorials/install-and-configure-docker/01.de.md
  tutorials/install-and-configure-docker/01.en.md
  tutorials/install-and-configure-ntp/01.de.md
  tutorials/install-and-configure-ntp/01.en.md
  tutorials/install-and-configure-proftpd/01.de.md
  tutorials/install-and-configure-proftpd/01.en.md
  tutorials/install-and-configure-proxmox_ve/01.de.md
  tutorials/install-and-configure-proxmox_ve/01.en.md
  tutorials/install-lamp-on-ubuntu-debian/01.en.md
  tutorials/install-lamp-server-on-centos-7/01.en.md
  tutorials/install-outline-vpn-server/01.en.md
  tutorials/install-public-ntp-server-on-debian-ubuntu/01.en.md
  tutorials/install-teamspeak3-server/01.de.md
  tutorials/install-teamspeak3-server/01.en.md
  tutorials/install-turn-stun-server-on-debian-ubuntu-with-coturn/01.en.md
  tutorials/installing-the-r8168-driver/01.de.md
  tutorials/installing-the-r8168-driver/01.en.md
  tutorials/lsi-raid-controller/01.de.md
  tutorials/lsi-raid-controller/01.en.md
  tutorials/private-cloud-additional-floating-pool/01.de.md
  tutorials/private-cloud-additional-floating-pool/01.en.md
  tutorials/prosody-on-debian9/01.en.md
  tutorials/rclone-basics/01.en.md
  tutorials/real-time-apps-with-go-and-reactjs/01.en.md
  tutorials/resize-ext-partition/01.de.md
  tutorials/resize-ext-partition/01.en.md
  tutorials/setup-mailserver-with-mailcow/01.en.md
Labels: ready

#94 Update Headings
  tutorials/rclone-basics/01.en.md
Labels: review wanted

#71 Install the latest version of php/nginx and MariaDB/ProFTPD (LEMP) server on Debian 9.x
  tutorials/install-configure-php-nginx-mariadb-proftpd-debian-9.x/01.en.md
  tutorials/install-configure-php-nginx-mariadb-proftpd-debian-9.x/01.zh.md
Labels: ready

#91 Cronjob email reports via ssmtp
  tutorials/cron-email-notifications/01.en.md
Labels: ready

#92 How to enable the integrated iGPU for Intel CPUs
  tutorials/howto-enable-igpu/01.de.md
  tutorials/howto-enable-igpu/01.en.md
Labels: ready

#99 Replace XML/HTML tag in template.md
  tutorial-template.md
Labels: review wanted

#72 Created tutorial on how to setup a game server with AMP
  tutorials/game-server-with-amp/01.en.md
Labels: ready

#101 Revert "Install the latest version of php/nginx and MariaDB/ProFTPD (LEMP) server on Debian 9.x"
  tutorials/install-configure-php-nginx-mariadb-proftpd-debian-9.x/01.en.md
  tutorials/install-configure-php-nginx-mariadb-proftpd-debian-9.x/01.zh.md
Labels: enhancement, invalid, review wanted

#49 Install and use SFTPClone
  tutorials/install-and-configure-sftpclone/01.de.md
  tutorials/install-and-configure-sftpclone/01.en.md
Labels: Importing from Wiki

#36 WIP: Realtimeapps v2
  tutorials/.keep
  tutorials/real-time-apps-with-go-and-reactjs/01.en.md
  tutorials/real-time-apps-with-go-and-reactjs/02.en.md
  tutorials/real-time-apps-with-go-and-reactjs/preview.gif
Labels: ready

#97 Setup monitoring for Managed Server based on the Monitoring Plugins
  tutorials/setup-monitoring-on-managed-server/01.en.md
Labels: ready

#90 Install & Configure Wordpress
  tutorials/install-and-configure-wordpress-on-centos-7/01.en.md
  tutorials/install-and-configure-wordpress-on-centos-7/images/01-first-page-wp.png
  tutorials/install-and-configure-wordpress-on-centos-7/images/02-example-db-configure.png
  tutorials/install-and-configure-wordpress-on-centos-7/images/03-db-configure-success.png
  tutorials/install-and-configure-wordpress-on-centos-7/images/04-wp-site-configure.png
  tutorials/install-and-configure-wordpress-on-centos-7/images/05-wp-site-configure-success.png
  tutorials/install-and-configure-wordpress-on-centos-7/images/06-wp-login-pages.png
  tutorials/install-and-configure-wordpress-on-centos-7/images/07-db-error.png
  tutorials/install-and-configure-wordpress-on-centos-7/images/08-wp-cannot-write.png
Labels: ready

#102 Securing tmp Folder of Webserver
  tutorials/secure-tmp-folder/01.en.md
Labels: ready

#105 add Install SolusVM with OpenVZ and KVM nodes tutorial
  tutorials/install-solusvm-with-openvz-and-kvm-nodes/01.en.md
Labels: ready

#104 Install IonCube Loader on CentOS 6
  tutorials/how-to-install-ioncube-loader-centos-6
Labels: ready
