Repository hetzneronline/community-content, pull requests merged in 2019-05, with the labels that each got.

#78 Ip sec nat
  tutorials/ipsec_nat/01.de.md
  tutorials/ipsec_nat/01.en.md
Labels: Importing from Wiki, WIP

#116 Add Tutorial Danted Socks5 Proxy
  tutorials/install-and-configure-danted-proxy-socks5/01.en.md
Labels: WIP

#125 Hcloud Ansible
  tutorials/howto-hcloud-ansible/01.en.md
Labels: ready

#132 Install and configure docker
  tutorials/install-and-configure-docker/01.de.md
  tutorials/install-and-configure-docker/01.en.md
  tutorials/install-and-configure-docker/01.ru.md
Labels: Existing tutorial, review wanted, translation

#136 Install and configure proftpd
  tutorials/install-and-configure-proftpd/01.de.md
  tutorials/install-and-configure-proftpd/01.en.md
  tutorials/install-and-configure-proftpd/01.ru.md
Labels: Existing tutorial, review wanted, translation

#137 configuring-windows-remote-desktop-services RU-translation and fix EN…
  tutorials/configuring-windows-remote-desktop-services/01.en.md
  tutorials/configuring-windows-remote-desktop-services/01.ru.md
Labels: Existing tutorial, translation

#120 How to check and change hostname of debian 9
  tutorials/check-and-change-hostname-on-debian-9/01.en.md
Labels: ready

#121 Add "Install a FEMP Stack on FreeBSD 12"
  tutorials/install-a-femp-stack-on-freebsd-12/01.en.md
  tutorials/install-a-femp-stack-on-freebsd-12/images/01-welcometonginx.png
  tutorials/install-a-femp-stack-on-freebsd-12/images/02-phpinfo.png
Labels: ready

#130 How to Install Zabbix on CentOS 7
  tutorials/install-zabbix-on-centos-7/01.en.md
  tutorials/install-zabbix-on-centos-7/zabbix-1.png
  tutorials/install-zabbix-on-centos-7/zabbix-2.png
  tutorials/install-zabbix-on-centos-7/zabbix-3.png
  tutorials/install-zabbix-on-centos-7/zabbix-4.png
  tutorials/install-zabbix-on-centos-7/zabbix-5.png
  tutorials/install-zabbix-on-centos-7/zabbix-6.png
  tutorials/install-zabbix-on-centos-7/zabbix-7.png
  tutorials/install-zabbix-on-centos-7/zabbix-8.png
Labels: ready

#138 Translation (RU): Changing the TLER Time
  tutorials/changing-tler-time/01.de.md
  tutorials/changing-tler-time/01.en.md
  tutorials/changing-tler-time/01.ru.md
Labels: official, translation

#143 Translation (RU): install-and-configure-proxmox_ve
  tutorials/install-and-configure-proxmox_ve/01.en.md
  tutorials/install-and-configure-proxmox_ve/01.ru.md
Labels: official, translation
