Repository hetzneronline/community-content, pull requests merged in 2019-10, with the labels that each got.

#203 Translation (RU): Setup your own Mailserver with Mailcow
  tutorials/setup-mailserver-with-mailcow/01.en.md
  tutorials/setup-mailserver-with-mailcow/01.ru.md
Labels: official, translation

#206 pfSense Private Network Tutorial: Upload/Performance fix
  tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks/01.en.md
Labels: Existing tutorial, ready

#193 Translation (RU): Secure TMP Folder on Webserver against execution
  tutorials/secure-tmp-folder/01.en.md
  tutorials/secure-tmp-folder/01.ru.md
Labels: official, translation

#199 Add "Create and install custom CentOS 8 image" tutorial
  tutorials/create-and-install-custom-centos-8-image/01.en.md
Labels: ready
