Repository hetzneronline/community-content, pull requests merged in 2019-11, with the labels that each got.

#205 Create A Secure Ubuntu 18.04 Snapshot on Hetzner Cloud
  tutorials/create-secure-ubuntu-18-04-snapshot/01.en.md
  tutorials/create-secure-ubuntu-18-04-snapshot/images/create_server.png
Labels: WIP

#210 Translation (RU): Install and Configure Wordpress on CentOS 7
  tutorials/install-and-configure-wordpress-on-centos-7/01.en.md
  tutorials/install-and-configure-wordpress-on-centos-7/01.ru.md
Labels: official, ready, translation

#192 Translation (RU): Managing Multiple Cloud Remotes with Hetzner
  tutorials/rclone-basics/01.en.md
  tutorials/rclone-basics/01.ru.md
Labels: WIP, official, translation
