Repository hetzneronline/community-content, pull requests merged in 2019-09, with the labels that each got.

#21 How to install and setup VMware vSphere
  tutorials/install-and-configure-routervm-for-vmware-vsphere/01.en.md
  tutorials/install-and-configure-routervm-for-vmware-vsphere/images/config-portgroups.png
  tutorials/install-and-configure-routervm-for-vmware-vsphere/images/config-routervm.png
  tutorials/install-and-configure-routervm-for-vmware-vsphere/images/config-vswitch.png
  tutorials/install-and-configure-vmware-vsphere/01.en.md
  tutorials/install-and-configure-vmware-vsphere/images/assign_mac.png
  tutorials/install-and-configure-vmware-vsphere/images/installed.png
Labels: ready

#128 Activate your Own Windows Server License | Hyper v on Windows
  tutorials/activate-own-Windows-License/01.en.md
  tutorials/activate-own-Windows-License/images/10.PNG
  tutorials/activate-own-Windows-License/images/11.PNG
  tutorials/activate-own-Windows-License/images/12.PNG
  tutorials/activate-own-Windows-License/images/13.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/01.en.md
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/10.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/11.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/12.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/13.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/2.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/3.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/4.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/6.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/7.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/8.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/9.PNG
  tutorials/setting-up-virtual-Windows-machine-HYPER-V/images/P1.PNG
Labels: ready

#182 tutorial for installing and configuring jupyterhub
  tutorials/install-and-configure-jupyterhub-on-ubuntu-18-04/01.en.md
  tutorials/install-and-configure-jupyterhub-on-ubuntu-18-04/images/add_users.png
  tutorials/install-and-configure-jupyterhub-on-ubuntu-18-04/images/admin.png
  tutorials/install-and-configure-jupyterhub-on-ubuntu-18-04/images/control_panel.png
  tutorials/install-and-configure-jupyterhub-on-ubuntu-18-04/images/login.png
  tutorials/install-and-configure-jupyterhub-on-ubuntu-18-04/images/pip_install.png
  tutorials/install-and-configure-jupyterhub-on-ubuntu-18-04/images/terminal_menu.png
Labels: ready

#183 New tutorial: Using GNU stow to manage manually compiled software
  tutorials/using-gnu-stow-to-manage-manually-compiled-software/01.en.md
Labels: ready

#174 Translation (RU): How-to: Hetzner Cloud Terraform Provider
  tutorials/howto-hcloud-terraform/01.en.md
  tutorials/howto-hcloud-terraform/01.ru.md
Labels: WIP, official, translation

#196 Translation (RU): Setting up a Game server with AMP
  tutorials/game-server-with-amp/01.en.md
  tutorials/game-server-with-amp/01.ru.md
Labels: official, translation

#119 Kubernetes installation guide
  tutorials/install-kubernetes-cluster/01.en.md
Labels: ready

#190 Add Node.js deploy with Docker
  tutorials/deploy-nodejs-with-docker/01.en.md
  tutorials/deploy-nodejs-with-docker/docker-hub-automated-builds-1.png
  tutorials/deploy-nodejs-with-docker/docker-hub-automated-builds-2.png
  tutorials/deploy-nodejs-with-docker/docker-hub-automated-builds-3.png
Labels: ready
