Repository hetzneronline/community-content, pull requests merged in 2019-06, with the labels that each got.

#133 How To Enable SFTP Without Shell Access on CentOS 7
  tutorials/add-sftp-only-user-no-ssh-access-on-centos-7/01.en.md
Labels: ready

#141 Installing and configuring OpenVPN server on Ubuntu/Debian with IPv6 support
  tutorials/install-and-configure-openvpn-on-ubuntu-and-debian/01.bg.md
  tutorials/install-and-configure-openvpn-on-ubuntu-and-debian/01.en.md
  tutorials/install-and-configure-openvpn-on-ubuntu-and-debian/images/installing-and-configuring-openvpn-on-ubuntu-and-debian.jpg
Labels: ready

#142 How to Install Matomo Analytics on CentOS 7
  tutorials/install-matomo-analytics-on-centos-7/01.en.md
  tutorials/install-matomo-analytics-on-centos-7/matomo-1.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-10.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-2.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-3.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-4.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-5.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-6.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-7.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-8.png
  tutorials/install-matomo-analytics-on-centos-7/matomo-9.png
Labels: ready

#148 Translation (RU): Install TURN/STUN Server on Debian/Ubuntu with coturn
  tutorials/install-turn-stun-server-on-debian-ubuntu-with-coturn/01.en.md
  tutorials/install-turn-stun-server-on-debian-ubuntu-with-coturn/01.ru.md
Labels: official, translation

#151 Translation (RU): Install a public NTP Server on Debian/Ubuntu
  tutorials/install-public-ntp-server-on-debian-ubuntu/01.en.md
  tutorials/install-public-ntp-server-on-debian-ubuntu/01.ru.md
Labels: official, translation

#140 How to setup mdadm Software RAID
  tutorials/howto-setup-mdadm/01.de.md
  tutorials/howto-setup-mdadm/01.en.md
Labels: ready

#144 Installing and configuring a Wireguard VPN server on Debian 9.9
  tutorials/install-and-configure-wireguard-vpn-debian/01.en.md
Labels: ready

#150 Translation (RU): Enabling the iGPU on Intel Processors
  tutorials/howto-enable-igpu/01.de.md
  tutorials/howto-enable-igpu/01.en.md
  tutorials/howto-enable-igpu/01.ru.md
Labels: official, translation

#139 How to Configure MySQL Master-Slave Replication on CentOS 7
  tutorials/configure-mariadb-master-slave-replication-on-centos-7/01.en.md
Labels: ready

#145 Basic cloud config (EN/DE)
  tutorials/basic-cloud-config/01.de.md
  tutorials/basic-cloud-config/01.en.md
Labels: ready

#149 typo fix
  tutorial-template.md
Labels: official

#152 Add "Setup a Firewall with IPFW on FreeBSD 12"
  tutorials/setup-a-firewall-with-ipfw-on-freebsd-12/01.en.md
Labels: ready

#153 Add "Setup a Tor Relay on FreeBSD 12"
  tutorials/setup-a-tor-relay-on-freebsd-12/01.en.md
Labels: ready
