Repository hetzneronline/community-content, pull requests merged in 2021-07, with the labels that each got.

#337 How to toggle password field in vuejs
  tutorials/how-to-toggle-password-field-in-vuejs/01.de.md
  tutorials/how-to-toggle-password-field-in-vuejs/01.en.md
  tutorials/how-to-toggle-password-field-in-vuejs/images/password-revealer.png
Labels: ready

#338 Added: Better Drive/Filesystem Overview with duf
  tutorials/better-drive-filesystem-overview-with-duf/01.de.md
  tutorials/better-drive-filesystem-overview-with-duf/01.en.md
  tutorials/better-drive-filesystem-overview-with-duf/images/duf.png
Labels: ready

#336 Add german translation for installing ubuntu 2004 with FDE
  tutorials/install-ubuntu-2004-with-full-disk-encryption/01.de.md
  tutorials/install-ubuntu-2004-with-full-disk-encryption/01.en.md
Labels: Existing tutorial, ready, translation

#334 Added: Simple Firewall Management with UFW
  tutorials/simple-firewall-management-with-ufw/01.de.md
  tutorials/simple-firewall-management-with-ufw/01.en.md
Labels: ready

#344 Tutorial: Secure Fedora Cloud Webserver - format & typo & extend
  tutorials/secure-fedora-webserver/01.en.md
Labels: Existing tutorial, ready

#346 Image link broken
  tutorials/configure-lb-cert-with-external-domain/01.en.md
Labels: Existing tutorial, ready

#342 Add tutorial for AWX without Kubernetes
  tutorials/awx-without-kubernetes/01.en.md
Labels: ready

#348 Remove shipyard
  tutorials/install-and-configure-docker/01.de.md
  tutorials/install-and-configure-docker/01.en.md
  tutorials/install-and-configure-docker/01.ru.md
  tutorials/install-and-configure-docker/images/586px-SiteEnabled.png
  tutorials/install-and-configure-docker/images/Addshipyard.png
  tutorials/install-and-configure-docker/images/Compose3.png
Labels: Existing tutorial, outdated content

#339 Added: How to install the Pterodactyl Game Server Management panel with the unofficial script made by vilhelmprytz
  tutorials/install-pterodactyl-panel-with-install-script/01.en.md
  tutorials/install-pterodactyl-panel-with-install-script/account.jpg
  tutorials/install-pterodactyl-panel-with-install-script/chooseoption.jpg
  tutorials/install-pterodactyl-panel-with-install-script/database.jpg
  tutorials/install-pterodactyl-panel-with-install-script/dns.jpg
Labels: ready

#316 Add Tutorial: on how to configure k8s authentication with load balancer
  tutorials/howto-k8s-authentication-with-load-balancer/01.de.md
  tutorials/howto-k8s-authentication-with-load-balancer/01.en.md
  tutorials/howto-k8s-authentication-with-load-balancer/images/loadbalancer-config.png
  tutorials/howto-k8s-authentication-with-load-balancer/images/loadbalancer-creation.png
  tutorials/howto-k8s-authentication-with-load-balancer/images/phpinfo.png
Labels: ready
